LOG_LEVEL = "info"
REDIS_URL_SSE = "{REDIS_CONNECTION_STRING}"
HMAC_SECRET = "{HMAC_SECRET_FROM_ENV}"
ALLOWED_EVENT_IDS = "*"
ALLOWED_EVENT_TYPES = "*"
REDIS_STREAM_NAME = "sse:events:prd"
REDIS_GROUP_NAME = "sse_consumers_prd"
