[server]
LOG_LEVEL = "error"
SERVER_PORT = 30000
ENABLE_MESSAGE_COMPRESSION = true
[auth]
HMAC_SECRET = "{HMAC_SECRET_FROM_ENV}"
ALLOWED_EVENT_IDS = "*"
ALLOWED_EVENT_TYPES = "*"
[redis]
REDIS_URL_SSE = "{REDIS_CONNECTION_STRING:redis://127.0.0.1:6379}"
QUEUE_NAME = "sse:events:dev"
CONSUMERS_GROUP_NAME = "sse_consumers_dev"
CONSUMERS_GROUP_ID = "1"
[send_fail_retries]
SEND_FAIL_RETRIES = 1
SEND_FAIL_DELAY_SECONDS = 2
DEAD_MESSAGE_PUSH_DEAD_QUEUE = true
